chat/urls.py
# chat/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('unread_rooms/', views.unread_chat_rooms, name='unread_rooms'),
    path('<str:user>/', views.room, name='room'),
    path('', views.index, name='index'),
]

mainapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from mainapp.view import login, home, add_manager, add_customer, \
    add_purchase, call_notes, attachments, task, calendars
from mainapp.view.import_export.export_data import export_xls, import_xls
from mainapp.view.pdfs import offers


app_name = 'mainapp'
urlpatterns = [
    path('', include(('mainapp.urls2', 'mainapp'), namespace='new')),

    path('heartbeat/', login.heartbeat, name='heartbeat'),
    path('', login.LoginView.as_view(), name='login'),
    path('logout', login.logout_view, name='logout'),

    # Home
    path('home/', home.HomeView.as_view(), name='home'),
    path('home/customer/<customer_id>/', home.CustomerHomeView.as_view(), name='customer_home'),

    path('manager/', add_manager.CreateManagerView.as_view(), name='add_manager'),
    path('manager/<int:pk>/', add_manager.UpdateManagerView.as_view(), name='edit_manager'),
    path('delete_manager/<manager_id>', add_manager.delete_manager, name='delete_manager'),

    path('customers/', add_customer.ListCustomerView.as_view(), name='list_customer'),
    path('customer/', add_customer.AddCustomerView.as_view(), name='add_customer'),
    path('customer/<int:pk>/', add_customer.UpdateCustomerView.as_view(), name='edit_customer'),
    path('update_customer/<int:pk>/', add_customer.update_customer, name='patch_customer'),
    path('delete/customer/<int:pk>/', add_customer.DeleteCustomerView.as_view(), name='delete_customer'),

    path('add_purchase/', add_purchase.AddPurchaseView.as_view(), name='add_purchase'),
    path('purchases/', add_purchase.ListPurchaseView.as_view(), name='list_purchase'),
    path('purchases/<int:pk>/', add_purchase.UpdatePurchaseView.as_view(), name='edit_purchase'),
    path('update_purchase/<int:pk>/', add_purchase.update_purchase, name='patch_purchase'),
    path('delete/purchases/<int:pk>/', add_purchase.DeletePurchaseView.as_view(), name='delete_purchase'),

    path('task_list/', task.TasksView.as_view(), name='open_task_list'),
    path('task/<int:pk>/', task.TaskUpdateView.as_view(), name='edit_task'),
    path('delete/task/<int:pk>/', task.DeleteTaskView.as_view(), name='delete_task'),
    path('mark_complete/<int:pk>/', task.mark_completed, name='mark_completed'),
    path('create_calendar_task/', task.create_task, name='create_calendar_task'),

    path('call_notes/<customer_id>/', call_notes.CallNotesCreateView.as_view(), name='add_call_notes'),
    path('call_notes/<customer_id>/<int:pk>/', call_notes.CallNotesUpdateView.as_view(), name='edit_call_notes'),
    path('delete/call_notes/<customer_id>/<int:pk>/', call_notes.CallNotesDeleteView.as_view(), name='delete_call_notes'),

    path('chat/', include(('chat.urls', 'chat'), 'chat')),

    path('<int:customer_id>/attachments/', attachments.AttachmentCreateView.as_view(), name='add_attachments'),
    path('<int:customer_id>/attachments/<int:pk>/', attachments.UpdateAttachmentView.as_view(), name='edit_attachments'),
    path('delete/<int:customer_id>/attachments/<int:pk>/', attachments.DeleteAttachmentView.as_view(), name='delete_attachments'),
    path('email/<int:customer_id>/attachment/<int:pk>/', attachments.email_attachment, name='email_attachment'),

    # attachment type settings
    path('attachment_type/', attachments.UpdateAttachmentTemplateView.as_view(), name='attachment_type'),

    # calendar
    path('calendar/', calendars.calendar, name='calendar'),

    # export and import urls
    path('export_data/', export_xls, name='export_xls'),
    path('import_data/', import_xls, name='import_xls'),

    path('offer/<customer_id>/', offers.download_offer, name='pdf_offer'),
    path('offer_confirm/<customer_id>/', offers.download_offer_confirm, name='pdf_offer_confirm'),
    path('install/<customer_id>/', offers.download_install, name='pdf_install'),
    path('invoice/<customer_id>/', offers.download_invoice, name='pdf_invoice'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

windows_crm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from des import urls as des_urls

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    path('django-des/', include(des_urls)),
    path("tinymce/", include("tinymce.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mainapp/models.py
import datetime

from django.core.validators import MinValueValidator
from django.db import models
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.models import AbstractUser, AbstractBaseUser
from django.db.models.aggregates import Sum, Count
from django.db.models.functions import Extract
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _

from mainapp.fields import ContentTypeRestrictedFileField
from mainapp.view.constants import CALL_NOTE_PRIORITY
from .usermanager import UserManager
from tinymce.models import HTMLField

# Create your models here.
class User(AbstractBaseUser, PermissionsMixin):
    first_name = models.CharField(_("First Name"), max_length=255)
    surname = models.CharField(_("Surname"), max_length=255)
    phone = models.CharField(_("Phone"), max_length=20, unique=True)
    username = models.CharField(_("Username"), max_length=255, unique=True)
    email = models.EmailField(_("Email"), max_length=255, unique=True)
    is_active = models.BooleanField(_("Active"), default=True)
    is_deleted = models.BooleanField(_('Deleted'), default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    is_staff = models.BooleanField(_('staff status'), default=False)

    objects = UserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['phone', 'first_name', 'email']

    def __str__(self):
        return self.first_name + " " + self.surname

    @classmethod
    def fetch(cls, username=None, user_id=None, is_superuser=False):
        try:
            if is_superuser is not None:
                user = cls.objects.filter(is_superuser=is_superuser)
            else:
                user = cls.objects.all()

            if username:
                user = user.filter(username=username).first()
            elif user_id:
                user = user.filter(id=user_id).first()

            return user
        except Exception as e:
            print("Exception occurs while fetching User: Error: {}".format(str(e)))
            return None


GENDER_CHOICES = (
    ('Male', _('Male')),
    ('Female', _('Female'))
)
PURPOSE_CHOICES = (
    ('Comapny', _('Company')),
    ('individual', _('individual')),
    ('Family', _('Family'))
)
OFFER_CHOICES = (
    ('Email', _('Via Email')),
    ('Letter', _('Via Letter')),
)
ATTACHMENT_TYPE_CHOICES = (
    ('offer', _('offer')),
    ('offer_confirmation', _('offer confirmation')),
    ('install', _('install')),
    ('invoice', _('invoice'))
)
CALL_NOTE_PRIORITY_CHOICES = (
    (CALL_NOTE_PRIORITY.high, _('Not started')),
    (CALL_NOTE_PRIORITY.medium, _('Pending In Work')),
    (CALL_NOTE_PRIORITY.low, _('Finished')),
)


class Customer(models.Model):
    def auto_code():
        number = Customer.objects.count()
        if number is None:
            return 6112
        else:
            return int(number) + 1

    customer_code = models.PositiveIntegerField(_("Customer Code"), default=auto_code, unique=True)
    first_name = models.CharField(_("first name"), max_length=255)
    offer_id = models.CharField(_("offer id"), max_length=255, blank=True,
                                null=True)
    invoice_id = models.CharField(_("Invoice ID"), max_length=255, blank=True,
                                  null=True)
    street = models.CharField(_("street"), max_length=500)
    postcode = models.CharField(_("postcode"), max_length=255)
    place = models.CharField(_("place"), max_length=255)
    surname = models.CharField(_("surname"), max_length=255)
    phone = models.CharField(_("Phone"), max_length=20, unique=True,
                             default='N.A')
    mobile = models.CharField(_("Mobile"), max_length=20, null=True, blank=True,
                              default='N.A')
    email = models.CharField(_("Email"), max_length=120, null=True, blank=True,
                             default='N.A')
    birthday = models.DateField(_("Birthday"), null=True, blank=True)
    is_active = models.BooleanField(_('active'), default=True)
    is_deleted = models.BooleanField(_('deleted'), default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    gender = models.CharField(_("gender"), max_length=100, choices=GENDER_CHOICES, null=True, blank=True)
    purpose = models.CharField(_("purpose"), max_length=100, choices=PURPOSE_CHOICES, null=True, blank=True)

    @classmethod
    def create(cls, first_name, street, postcode, place, surname, phone, mobile, gender, purpose):
        try:
            customer = cls.objects.create(first_name=first_name, street=street, postcode=postcode, place=place,
                                          surname=surname, phone=phone, mobile=mobile, gender=gender, purpose=purpose)
            return customer
        except Exception as e:
            print("Exception occurs while creating Customer. Error: {}".format(str(e)))
            return None

    @classmethod
    def fetch(cls, customer_id=None, name=None):
        try:
            customer = cls.objects.all()
            if customer_id:
                customer = customer.filter(id=customer_id).last()

            if name:
                customer = customer.filter(first_name__contains=name)

            return customer
        except Exception as e:
            print("Exception occurs while fetching Customer. Error: {}".format(str(e)))
            return None

    def __str__(self):
        return self.first_name + " " + self.surname


class CallNotes(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='call_notes')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='call_notes')
    notes = models.TextField(_("notes"), max_length=1000)
    status = models.PositiveSmallIntegerField(choices=CALL_NOTE_PRIORITY_CHOICES,
                                              default=CALL_NOTE_PRIORITY.high)
    created = models.DateTimeField(null=True)

    def save(self, *args, **kwargs):
        self.created = datetime.datetime.now()
        return super(CallNotes, self).save(*args, **kwargs)

    @classmethod
    def create(cls, customer_id, user_id, notes):
        try:
            call_notes = cls.objects.create(customer_id=customer_id, user_id=user_id, notes=notes)
            return call_notes

        except Exception as e:
            print("Exception occurs while creating Call Notes. Error: {}".format(str(e)))
            return None

    @classmethod
    def fetch(cls, customer_id):
        try:
            call_notes = cls.objects.filter(customer_id=customer_id)
            return call_notes

        except Exception as e:
            print("Exception occues while fetching Call Notes. Error: {}".format(str(e)))
            return None


class PurchaseRecord(models.Model):
    customer = models.OneToOneField(Customer, verbose_name=_("Customer"), on_delete=models.CASCADE,
                                    related_name='purchase_record')
    module_manufacturer = models.CharField(_("manufacturer"), max_length=255, null=True)
    watt = models.PositiveIntegerField(_("watt"), null=True, default=0)
    module_count = models.PositiveIntegerField(_("module count"), null=True, default=0)

    with_battery = models.BooleanField(_("with battery"), blank=True, default=False, null=True)
    manufacturer = models.CharField(_("manufacturer"), max_length=255, null=True, blank=True)
    kwh = models.CharField(_("Kw/H"), max_length=255, blank=True, null=True)
    manufacturer2 = models.CharField(_('Manufacturer'), max_length=255, blank=True, null=True)
    kwh2 = models.CharField(_('Kw/H'), max_length=255, blank=True, null=True)

    price_without_tax = models.FloatField(_("price without tax"), help_text=_("Price in Euro (€)"), null=True,
                                          validators=[MinValueValidator(0, _("Should be above 0"))],
                                          default=0)

    offer_by = models.CharField(_("offer by"), choices=OFFER_CHOICES, max_length=16, null=True)
    # OFFER INFORMATION
    offer_date = models.DateField(_("offer date"), blank=True, null=True)
    reseller_name = models.ForeignKey("Reseller", on_delete=models.SET_NULL,
                                      null=True, blank=True, related_name='purchases', verbose_name=_("Reseller"))
    declined = models.BooleanField(_("declined"), default=False, null=True, blank=True)
    # TECHNICAL DETAILS
    date_sent = models.DateField(_('date sent'), null=True, blank=True)
    project_planning_created = models.BooleanField(_('project planning created'),
                                                   blank=False, default=False)
    dc_term = models.DateField(_('DC Term'), blank=True, null=True)
    dc_mechanic = models.ForeignKey('Mechanic', on_delete=models.SET_NULL,
                                    null=True, blank=True, related_name='dc_purchases', verbose_name=_("DC Mechanic"))
    ac_term = models.DateField(_('AC Term'), blank=True, null=True)
    ac_mechanic = models.ForeignKey("Mechanic", on_delete=models.SET_NULL,
                                    null=True, blank=True, related_name='ac_purchases', verbose_name=_("AC Mechanic"))
    # INFORMATION FOR THE ROOF
    roof_type = models.CharField(_("roof type"), max_length=255, null=True, blank=True)
    roof_tilt = models.FloatField(_("roof tilt"), help_text=_("in Degrees"), null=True, blank=True)
    alignment = models.CharField(_("alignment"), max_length=64, null=True, blank=True)
    module_area = models.FloatField(_("module area"), help_text=_("Area in meter squared (m2)"), null=True, blank=True,
                                    validators=[MinValueValidator(0, _("Should be above 0"))],
                                    default=0)

    extra_details = models.TextField(_("extra details"), blank=True, null=True)

    # module_type = models.CharField(max_length=255)
    # memory_type = models.CharField(max_length=255)
    #
    # installation_date = models.DateTimeField()

mainapp/forms/add_customer.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column, HTML

from mainapp.forms.mixins import LabelAdder
from mainapp.models import Customer, GENDER_CHOICES, PURPOSE_CHOICES


class CustomerForm(LabelAdder, forms.ModelForm):
    class Meta:
        model = Customer
        fields = ['purpose', 'gender', 'first_name', 'surname', 'offer_id', 'invoice_id', 'street',
                  'place', 'postcode', 'phone', 'mobile', 'email', 'birthday']
        widgets = {
            'birthday': forms.DateInput(attrs={'type': 'date'})
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # converting to string because form cannot handle date internationalization
        if self.instance and self.instance.id:
            self.initial['birthday'] = str(self.initial['birthday'])


class CustomerAddForm(CustomerForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name in self.fields.keys():
            self.fields[field_name].widget.attrs['class'] = 'form-control'


class CustomerUpdateForm(CustomerForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Column(
                *[Row(field_name, css_class='form-group')
                  for field_name in list(self.fields.keys())[:len(self.fields.keys())//2 + 1]],
                css_class='col-md-6'
            ), Column(
                *[Row(field_name, css_class='form-group')
                  for field_name in list(self.fields.keys())[(len(self.fields.keys()) // 2 + 1):]],
                css_class='col-md-6'
            ),
        )

mainapp/forms/call_notes.py
from django import forms

from mainapp.forms.mixins import LabelAdder
from mainapp.models import CallNotes


class AddCallNotesForm(LabelAdder, forms.ModelForm):
    class Meta:
        model = CallNotes
        fields = ['notes', 'status']

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request", None)
        self.customer_id = kwargs.pop("customer_id", None)
        if not self.request or not self.customer_id:
            raise AttributeError("request missing")
        super().__init__(*args, **kwargs)
        for field_name in self.fields.keys():
            self.fields[field_name].widget.attrs['class'] = 'form-control'

    def save(self, commit=True):
        instance = super(AddCallNotesForm, self).save(commit=False)
        instance.user = self.request.user
        instance.customer_id = self.customer_id
        instance.save()

mainapp/views.py
from django.shortcuts import render

# Create your views here.

mainapp/templates/add_purchase.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block css %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/css/bootstrap-select.min.css">
{% endblock %}

{% block content %}

    <div class="dashboard-content-container" data-simplebar>
        <div class="dashboard-content-inner">
            <div class="row">
                <div class="col-md-6">
                    <h1>{% if operation %} {{operation}} {% else %} {% trans 'Add Purchase' %} {% endif %}</h1>
                </div>
                <div class="col-md-6" style="text-align: right;">
                    <button class="button" onclick="new_customer_btn()">{% blocktrans %}Add Customer{% endblocktrans %}</button>
                </div>
            </div>
            <br/>
            <form method="POST">
                {% csrf_token %}
                <div id="div_id_customer" class="form-group">
                    <label for="id_customer" class="">
                        {% trans 'Customer' %}* {% if form.instance %}: <b>{{ form.instance.customer }}</b> {% endif %}
                    </label>
                    <div class="">
                        <select name="customer" class="form-control selectpicker" id="id_customer" data-live-search="true" title="Customer">
                            {% for val, display in form.fields.customer.choices %}
                                <option value="{{ val }}" data-tokens="{{ val }} {{ display }}">{{ display }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                {% crispy form %}
            </form>
        </div>
    </div>

{% endblock %}

{% block script %}
    <script>
        function new_customer_btn() {
            window.location = "{% url 'mainapp:add_customer' %}";
        }
        $('#id_module_area').change(function() {
            $('#total_area').html($('#id_module_area').val()*$('#id_module_count').val());
        });
        $('#id_watt').change(function() {
            $('#id_kwp').html($('#id_watt').val()*$('#id_module_count').val()/1000);
        });
        $('#id_module_count').change(function() {
            $('#id_kwp').html($('#id_watt').val()*$('#id_module_count').val()/1000);
            $('#total_area').html($('#id_module_area').val()*$('#id_module_count').val());
        });
    </script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.12.4/dist/js/bootstrap-select.min.js"></script>

{% endblock %}

mainapp/templates/attachments.html
{% extends 'dashboard.html' %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block maincontent %}
    <div class="dashboard-content-container" data-simplebar>
		<div class="dashboard-content-inner" >
            {% if operation %}
                <p style="padding-bottom: 15px;">
                    <a href="{% url 'mainapp:add_attachments' customer_id=customer_id %}">
                        <button class="button"><i class="icon-material-outline-arrow-back"></i> Go Back</button>
                    </a>
                </p>
            {% endif %}
            <h1>{% if operation %} {{ operation }} {% else %} {% trans "Add New Attachment" %} {% endif %}</h1>
            <br/>
            <form method="POST" enctype="multipart/form-data" id="id_create_attachment" class="contact100-form validate-form">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="button">{% trans 'Submit' %}</button>
            </form>

            <div class="tasks-list-container compact-list margin-top-35">
                {% if object_list %}
                    <table class="table">
                    {% for attachment in object_list %}
                        <tr>
                            <td>{{ attachment.file_name }}.{{ attachment.file_type }}</td>
                            <td>{{ attachment.uploaded_by }}</td>
                            <td>{{ attachment.created_at }}</td>
                            <td>
                                <a style="text-decoration: none" href="{% url 'mainapp:edit_attachments' customer_id=customer_id pk=attachment.id %}" class="">&nbsp &nbsp<i class="icon-feather-edit"></i><span> {% trans 'Edit' %}</span></a>
                                <a style="text-decoration: none" href="{% url 'mainapp:delete_attachments' customer_id=customer_id pk=attachment.id %}" class="">&nbsp &nbsp<i class="icon-material-outline-delete"></i><span class="danger"> {% trans 'Delete' %}</span></a>
                            </td>
                            <td>
                                <a style="text-decoration: none" target="_blank" href="{{ MEDIA_URL }}{{ attachment.upload.url }}">[ <i class="icon-feather-download"></i><span> {% trans 'Download' %} ]</span></a>
                            </td>
                            <td>
                                <a style="text-decoration: none" target="_blank" href="{% url 'mainapp:email_attachment' customer_id=customer_id pk=attachment.pk %}">[ <i class="icon-feather-mail"></i><span> {% trans 'Email' %} ]</span></a>
                            </td>
                        </tr>
                    {% endfor %}
                    </table>
                {% endif %}
            </div>
        </div>
    </div>

    <script>
    </script>

{% endblock %}

mainapp/templates/head.html
{% load static %}

    <meta charset="UTF-8">

    <!-- =============== Viewport =============== -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- =============== Description =============== -->
    <meta name="description" content=""/>

    <!-- =============== keywords =============== -->
    <meta name="keywords" content=""/>

    <!-- =============== Bootstrap =============== -->
    <link rel="stylesheet" href="{% static '/dashboard-assets/css/bootstrap.min.css' %}"/>

    <!-- =============== Favicon =============== -->
    <link href="{% static '/dashboard-assets/img/logo.png" rel="shortcut icon' %}"/>

    <!-- =============== Fontawsome =============== -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
          integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">


    <!-- =============== Main_CSS =============== -->
    <link rel="stylesheet" href="{% static '/dashboard-assets/css/style.css' %}"/>

    <!-- =============== CUSTOM_CSS =============== -->
    <link rel="stylesheet" href="{% static '/dashboard-assets/css/custom_style.css' %}"/>

    <!-- =============== Responsive_CSS =============== -->
    <link rel="stylesheet" href="{% static '/dashboard-assets/css/responsive.css' %}"/>

mainapp/templates/navsection.html
{% load i18n %}
{% load static %}
{#    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>#}
{#  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>#}
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

<section>
    <div class="sidenav">
        <div class="logo-area mb-5" style="height: 9.5%; min-height: 50px; position: relative">
            <div class="vertical-center">
                <a href="/">
                    <img src="{% static '/dashboard-assets/img/logo.png' %}" class="img-fluid" alt="Company Logo">
                </a>
            </div>
        </div>
        <a href="/"><i class="fas fa-home"></i>&nbsp {% trans 'Dashboard' %}</a>
{#        <a href=""><i class="fas fa-user">&nbsp {{ customer.first_name }} {{ customer.surname }}</i></a>#}
{#        <a href=""><i class="fas fa-envelope">&nbsp {{ customer.email }}</i></a>#}
        <a href="/chat/"><i class="fas fa-comment"></i>&nbsp {% trans 'Chat' %} <span class="chat_badge"></span></a>
        <a href="/task_list/"><i class="fas fa-calendar-check"></i>&nbsp {% trans 'To Do' %}</a>
        <a href="{% url 'mainapp:calendar' %}"><i class="fas fa-calendar-alt"></i>&nbsp {% trans 'Calendar' %}</a>
        <a href="{% url 'mainapp:attachment_type' %}"><i class="fas fa-cog"></i>&nbsp {% trans 'Settings' %}</a>
        <div style="margin-top: 50px;"></div>
        <a href={% url 'mainapp:list_customer' %}><i class="fas fa-plus"></i>&nbsp <span><strong>{% trans 'Customer' %}</strong></span></a>
        <a href="{% url 'mainapp:list_purchase' %}"><i class="fas fa-plus"></i>&nbsp <span><strong>{% trans 'Purchase' %}</strong></span></a>
        {% if user.is_staff %}
            <a href="{% url 'mainapp:add_manager' %}"><i class="fas fa-plus"></i>&nbsp <span><strong>{% trans 'Manager' %}</strong></span></a>
        {% endif %}
        <a href="{% url 'mainapp:logout' %}" style="color:red; font-weight:bold; margin-top: 25px; margin-bottom: 10px">{% trans 'Logout' %}</a>
        <div class="login-bottom-area">
            <div><i class="fas fa-headset"></i> {% trans 'Support' %}</div>
            <div>info@desativ-tech.de</div>
            <div>+49 89 2000 12 70</div>
            <div><a href="https://www.desativ-tech.de">www.desativ-tech.de</a></div>
        </div>
    </div>
</section>
<section class="top-area">

    <!-- Start nav area -->
    <nav class="navbar navbar-expand-lg navbar-light navbar-default">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
        <form method="POST" action="{% url 'mainapp:home' %}" class="form-inline my-4 my-lg-2">
          {% csrf_token %}
          <input name="name" required class="form-control mr-sm-2" type="search" placeholder={% trans 'Search' %} aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">{% trans 'Search' %}</button>
        </form>
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <li class="nav-item">
            <a class="nav-link " href="">
                <i class="fas fa-bell bell"></i>
            </a>
          </li>
          <li class="nav-item">
              <div class="horizontal">
                <a class="nav-link disabled" href="#">
                    <div class="profile-area">
                        {{ request.user.first_name|title }} {{ request.user.surname|title }}
                        <p>Anwesend</p>
                    </div>
                </a>
                  <a class="navbar-brand" href="#">
                      <div class="circle-container">
                    <img src="https://picsum.photos/seed/{{ request.user.id }}/200/200" class="rounded-circle"
                            alt="">
                          </div>
                  </a>
              </div>
          </li>
            <li>
                <form method="POST" action="/i18n/setlang/" id="lang-form">
                    {% csrf_token %}
                    <select name="language" value="" onchange="$('#lang-form').submit()">
                        <option value="">--</option>
                        <option value="en">En</option>
                        <option value="de">De</option>
                    </select>
                    <button hidden type="submit">Sub</button>
                </form>
            </li>
        </ul>
      </div>
    </nav>
    <!-- Finished nav area -->

</section>

<script>
    $.ajax({
        url: "{% url 'mainapp:chat:unread_rooms' %}",
        type: 'get',
        success: function(data) {
            if (data.count) {
                $('.chat_badge').html(data.count);
            }
        }
    });

    const notificationSocket = new WebSocket(
        'ws://'
        + window.location.host
        + '/ws/chat/notification/'
    );

    notificationSocket.onmessage = function(e) {
        const data = JSON.parse(e.data);
        if ({{ request.user.id }} == data.for) {
            $('.chat_badge').html('Nachricht vorhanden');
        }
    };
</script>