chat/urls.py
# chat/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('unread_rooms/', views.unread_chat_rooms, name='unread_rooms'),
    path('<str:user>/', views.room, name='room'),
    path('', views.index, name='index'),
]

mainapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from mainapp.view import login, home, add_manager, add_customer, \
    add_purchase, call_notes, attachments, task, calendars
from mainapp.view.import_export.export_data import export_xls, import_xls
from mainapp.view.pdfs import offers


app_name = 'mainapp'
urlpatterns = [
    path('', include(('mainapp.urls2', 'mainapp'), namespace='new')),

    path('heartbeat/', login.heartbeat, name='heartbeat'),
    path('', login.LoginView.as_view(), name='login'),
    path('logout', login.logout_view, name='logout'),

    # Home
    path('home/', home.HomeView.as_view(), name='home'),
    path('home/customer/<customer_id>/', home.CustomerHomeView.as_view(), name='customer_home'),

    path('manager/', add_manager.CreateManagerView.as_view(), name='add_manager'),
    path('manager/<int:pk>/', add_manager.UpdateManagerView.as_view(), name='edit_manager'),
    path('delete_manager/<manager_id>', add_manager.delete_manager, name='delete_manager'),

    path('customers/', add_customer.ListCustomerView.as_view(), name='list_customer'),
    path('customer/', add_customer.AddCustomerView.as_view(), name='add_customer'),
    path('customer/<int:pk>/', add_customer.UpdateCustomerView.as_view(), name='edit_customer'),
    path('update_customer/<int:pk>/', add_customer.update_customer, name='patch_customer'),
    path('delete/customer/<int:pk>/', add_customer.DeleteCustomerView.as_view(), name='delete_customer'),

    path('add_purchase/', add_purchase.AddPurchaseView.as_view(), name='add_purchase'),
    path('purchases/', add_purchase.ListPurchaseView.as_view(), name='list_purchase'),
    path('purchases/<int:pk>/', add_purchase.UpdatePurchaseView.as_view(), name='edit_purchase'),
    path('update_purchase/<int:pk>/', add_purchase.update_purchase, name='patch_purchase'),
    path('delete/purchases/<int:pk>/', add_purchase.DeletePurchaseView.as_view(), name='delete_purchase'),

    path('task_list/', task.TasksView.as_view(), name='open_task_list'),
    path('task/<int:pk>/', task.TaskUpdateView.as_view(), name='edit_task'),
    path('delete/task/<int:pk>/', task.DeleteTaskView.as_view(), name='delete_task'),
    path('mark_complete/<int:pk>/', task.mark_completed, name='mark_completed'),
    path('create_calendar_task/', task.create_task, name='create_calendar_task'),

    path('call_notes/<customer_id>/', call_notes.CallNotesCreateView.as_view(), name='add_call_notes'),
    path('call_notes/<customer_id>/<int:pk>/', call_notes.CallNotesUpdateView.as_view(), name='edit_call_notes'),
    path('delete/call_notes/<customer_id>/<int:pk>/', call_notes.CallNotesDeleteView.as_view(), name='delete_call_notes'),

    path('chat/', include(('chat.urls', 'chat'), 'chat')),

    path('<int:customer_id>/attachments/', attachments.AttachmentCreateView.as_view(), name='add_attachments'),
    path('<int:customer_id>/attachments/<int:pk>/', attachments.UpdateAttachmentView.as_view(), name='edit_attachments'),
    path('delete/<int:customer_id>/attachments/<int:pk>/', attachments.DeleteAttachmentView.as_view(), name='delete_attachments'),
    path('email/<int:customer_id>/attachment/<int:pk>/', attachments.email_attachment, name='email_attachment'),

    # attachment type settings
    path('attachment_type/', attachments.UpdateAttachmentTemplateView.as_view(), name='attachment_type'),

    # calendar
    path('calendar/', calendars.calendar, name='calendar'),

    # export and import urls
    path('export_data/', export_xls, name='export_xls'),
    path('import_data/', import_xls, name='import_xls'),

    path('offer/<customer_id>/', offers.download_offer, name='pdf_offer'),
    path('offer_confirm/<customer_id>/', offers.download_offer_confirm, name='pdf_offer_confirm'),
    path('install/<customer_id>/', offers.download_install, name='pdf_install'),
    path('invoice/<customer_id>/', offers.download_invoice, name='pdf_invoice'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

windows_crm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from des import urls as des_urls

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    path('django-des/', include(des_urls)),
    path("tinymce/", include("tinymce.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mainapp/forms/add_customer.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column, HTML

from mainapp.forms.mixins import LabelAdder
from mainapp.models import Customer, GENDER_CHOICES, PURPOSE_CHOICES


class CustomerForm(LabelAdder, forms.ModelForm):
    class Meta:
        model = Customer
        fields = ['purpose', 'gender', 'first_name', 'surname', 'offer_id', 'invoice_id', 'street',
                  'place', 'postcode', 'phone', 'mobile', 'email', 'birthday']
        widgets = {
            'birthday': forms.DateInput(attrs={'type': 'date'})
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # converting to string because form cannot handle date internationalization
        if self.instance and self.instance.id:
            self.initial['birthday'] = str(self.initial['birthday'])


class CustomerAddForm(CustomerForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name in self.fields.keys():
            self.fields[field_name].widget.attrs['class'] = 'form-control'


class CustomerUpdateForm(CustomerForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Column(
                *[Row(field_name, css_class='form-group')
                  for field_name in list(self.fields.keys())[:len(self.fields.keys())//2 + 1]],
                css_class='col-md-6'
            ), Column(
                *[Row(field_name, css_class='form-group')
                  for field_name in list(self.fields.keys())[(len(self.fields.keys()) // 2 + 1):]],
                css_class='col-md-6'
            ),
        )

mainapp/forms/add_manager.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Row, Column

from mainapp.forms.mixins import LabelAdder
from mainapp.models import User


class ManagerForm(LabelAdder, forms.ModelForm):
    class Meta:
        model = User
        fields = ["first_name", "surname", "phone", 'username', 'email', 'password']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.instance and self.instance.id is not None:
            self.fields['email'].widget.attrs['readonly'] = True
            self.initial['password'] = ""
        for field_name in self.fields.keys():
            self.fields[field_name].widget.attrs['class'] = 'form-control'

        self.helper = FormHelper()
        self.helper.layout = Layout(
            Column(
                *[Row(field_name, css_class='form-group')
                  for field_name in list(self.fields.keys())[:len(self.fields.keys()) // 2 + 1]],
                css_class='col-md-6'
            ), Column(
                *[Row(field_name, css_class='form-group')
                  for field_name in list(self.fields.keys())[(len(self.fields.keys()) // 2 + 1):]],
                css_class='col-md-6'
            ),
        )

    def clean_email(self):
        if self.instance and self.instance.id:
            return self.instance.email
        return self.cleaned_data['email']

mainapp/forms/add_purchase_record.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column, HTML

from mainapp.forms.mixins import LabelAdder
from mainapp.models import PurchaseRecord


class PurchaseRecordForm(LabelAdder, forms.ModelForm):
    class Meta:
        model = PurchaseRecord
        exclude = ['created_at', 'is_active']
        widgets = {
            'offer_date': forms.DateInput(attrs={'type': 'date'}),
            'date_sent': forms.DateInput(attrs={'type': 'date'}),
            'dc_term': forms.DateInput(attrs={'type': 'date'}),
            'ac_term': forms.DateInput(attrs={'type': 'date'}),
            'project_planning_created': forms.Select(choices=((True, _('Yes')), (False, _('No')))),
            'date_of_receipt': forms.DateInput(attrs={'type': 'date'})
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, field in self.fields.items():
            self.fields[name].widget.attrs['class'] = 'form-control'
        if self.instance and self.instance.id:
            # customer is not required
            self.fields['customer'].required = False
            self.fields['reseller_name'].required = False
            self.fields['ac_mechanic'].required = False
            self.fields['dc_mechanic'].required = False
            # forms cannot handle i18n date change
            self.initial['offer_date'] = str(self.initial['offer_date'])
            self.initial['date_sent'] = str(self.initial['date_sent'])
            self.initial['dc_term'] = str(self.initial['dc_term'])
            self.initial['ac_term'] = str(self.initial['ac_term'])
        self.helper = FormHelper()
        self.helper.layout = Layout(
            # Row(
            #     Column('customer', css_class='form-group selectpicker col-md-12 mb-0', data_live_search="true"),
            #     css_class='form-row'
            # ),
            HTML('<h3>Module</h3>'),
            Row(
                Column('module_manufacturer', css_class='form-group col-md-12 mb-0'),
                css_class='form-row'
            ),
            Row(
                Column('watt', css_class='form-group col-md-3 mb-0'),
                HTML('<div class="col-md-1 mb-0"></div>'),
                Column('module_count', css_class='form-group col-md-4 mb-0'),
                HTML('<div class="col-md-2 mb-0"></div>'
                     '<p>'
                     'KWP:  <strong><div id="id_kwp"></div></strong>'
                     '</p>'
                     '<br/>'),
                css_class='form-row'
            ),
            HTML('<h3>%s</h3>' % _("Choose if there is battery system or not")),
            'with_battery',
            HTML(f'<h3>{_("With Battery")}</h3>'),
            Row(
                Column('manufacturer', css_class='form-group col-md-6 mb-0'),
                Column('kwh', css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            ),
            HTML('<h3>%s</h3>' % _("WR - Without Battery")),
            Row(
                Column('manufacturer2', css_class='form-group col-md-6 mb-0'),
                Column('kwh2', css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            ),
            HTML('<h3>%s</h3>' % _("Price")),
            'price_without_tax',
            HTML('<p>{}: 19%<br/>'.format(_("Tax"))),
            'offer_by',
            HTML('<h4>%s</h4><br/>' % _("Offer Details")),
            Row(
                Column('offer_date', css_class='form-group col-md-4 mb-0'),
                Column('reseller_name', css_class='form-group col-md-6 mb-0'),
                Column('declined', css_class='form-group col-md-2 mb-0'),
                css_class='form-row'
            ),
            HTML('<h4></h4><br/>' % _("Technical Details")),
            Row(
                Column('date_sent', css_class='form-group col-md-6 mb-0'),
                Column('project_planning_created', css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            ),
            Row(
                Column('dc_term', css_class='form-group col-md-6 mb-0'),
                Column('dc_mechanic', css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            ),
            Row(
                Column('ac_term', css_class='form-group col-md-6 mb-0'),
                Column('ac_mechanic', css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            ),
            Row(
                Column('date_of_receipt', css_class='form-group col-md-6 mb-0')
            ),
            HTML('<h4></h4><br/>' % _("Information of the Roof")),
            'roof_type',
            Row(
                Column('roof_tilt', css_class='form-group col-md-4 mb-0'),
                Column('alignment', css_class='form-group col-md-4 mb-0'),
                Column('module_area', css_class='form-group col-md-4 mb-0'),
                css_class='form-row'
            ),
            Row(
                Column('', css_class='form-group col-md-4 mb-0'),
                Column('', css_class='form-group col-md-4 mb-0'),
                HTML('<p>'
                     '%s: <div id="total_area"></div>' % _("Total Area of all modules") +
                     '</p>'
                     '<br/>'),
                css_class='form-row'
            ),
            'extra_details',
        )

    def clean(self):
        result = super(PurchaseRecordForm, self).clean()
        # if customer is not being updated from the front
        if not result.get('customer') and self.instance and self.instance.id:
            result['customer'] = self.instance.customer
        return result

mainapp/forms/attachments.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Column, Row
from django import forms

from mainapp.models import Attachments, AttachmentTemplate


class AttachmentForm(forms.ModelForm):
    class Meta:
        model = Attachments
        fields = ['file_name', 'upload']

    def __init__(self, *args, **kwargs):
        self.customer_id = kwargs.pop("customer_id", None)
        self.request = kwargs.pop("request", None)
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.customer_id = self.customer_id
        if self.request:
            instance.uploaded_by = self.request.user
        instance.save()


class AttachmentTemplateForm(forms.ModelForm):
    class Meta:
        model = AttachmentTemplate
        fields = ['subject', 'body']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name in self.fields.keys():
            self.fields[field_name].widget.attrs['class'] = 'form-control'

        self.helper = FormHelper()
        self.helper.layout = Layout(
            Column(
                *[Row(field_name, css_class='form-group')
                  for field_name in list(self.fields.keys())],
                css_class='col-md-12'
            )
        )

mainapp/forms/call_notes.py
from django import forms

from mainapp.forms.mixins import LabelAdder
from mainapp.models import CallNotes


class AddCallNotesForm(LabelAdder, forms.ModelForm):
    class Meta:
        model = CallNotes
        fields = ['notes', 'status']

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request", None)
        self.customer_id = kwargs.pop("customer_id", None)
        if not self.request or not self.customer_id:
            raise AttributeError("request missing")
        super().__init__(*args, **kwargs)
        for field_name in self.fields.keys():
            self.fields[field_name].widget.attrs['class'] = 'form-control'

    def save(self, commit=True):
        instance = super(AddCallNotesForm, self).save(commit=False)
        instance.user = self.request.user
        instance.customer_id = self.customer_id
        instance.save()

mainapp/forms/login.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

from mainapp.models import User


class LoginForm(forms.Form):
    username = forms.CharField(label=_('username'),
                               required=True,
                               max_length=255,
                               widget=forms.TextInput(
                                   attrs={
                                       'class': 'form-control',
                                       'placeholder': _('Username')
                                   }
                               ))

    password = forms.CharField(label=_('password'),
                               required=True,
                               max_length=255,
                               widget=forms.PasswordInput(
                                   attrs={
                                       'class': 'form-control',
                                       'placeholder': _('Password')
                                   }
                               ))

    def clean(self):
        username = self.cleaned_data['username']
        if not User.objects.filter(username__iexact=username).exists():
            raise ValidationError(
                "Username/Password does not match"
            )
        user = User.objects.get(username__iexact=username)
        password = self.cleaned_data['password']
        if not user.check_password(raw_password=password):
            raise ValidationError(
                "Username/Password does not match"
            )
        return self.cleaned_data

mainapp/views.py
from django.shortcuts import render

# Create your views here.

mainapp/templates/calendars/calendar.html
{% extends 'base.html' %}
{% load i18n %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="https://uicdn.toast.com/tui-calendar/latest/tui-calendar.css" />
    <!-- If you use the default popups, use this. -->
    <link rel="stylesheet" type="text/css" href="https://uicdn.toast.com/tui.date-picker/latest/tui-date-picker.css" />
    <link rel="stylesheet" type="text/css" href="https://uicdn.toast.com/tui.time-picker/latest/tui-time-picker.css" />

    <style>
    #menu-navi {
        background-color: rgb(192, 196, 153);
        padding-top: 10px;
    }
    </style>
{% endblock %}

{% block content %}
    <div id="menu">
        <div id="menu-navi">
            <div class="row">
                <div class="col-6">
                    <button type="button" onclick="onClickTodayBtn()" class="btn btn-secondary btn-sm">
                        -{% trans 'Today' %}-
                    </button>
                    <button type="button" onclick="moveToNextOrPrevRange(-1)" class="btn btn-secondary btn-sm move-day" data-action="move-prev">
                        <--
                    </button>
                    <button type="button" onclick="moveToNextOrPrevRange(1)" class="btn btn-secondary btn-sm move-day" data-action="move-next">
                        -->
                    </button>&nbsp;&nbsp;&nbsp;
                    <span id="cal-month"></span>.<span id="cal-year"></span>
                </div>
                <div class="col-6">
                    <div class="row">
                        <div class="col-4">
                            DC/AC
                            <input type="radio" id="cal_purchase" value="purchase" checked name="calType" onclick="showPurchase()" />
                        </div>
                        <div class="col-4">
                            {% trans 'Public Tasks' %}
                            <input type="radio" id="cal_tasks" value="public" name="calType" onclick="showTasks()" />
                        </div>
                        <div class="col-4">
                            {% trans 'Private Tasks' %}
                            <input type="radio" id="cal_private" value="private" name="calType" onclick="showPrivateTasks()" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <span id="renderRange" class="render-range"></span>
    </div>
    <div id="calendar"></div>
{% endblock %}

{% block script %}
    <script src="https://uicdn.toast.com/tui.code-snippet/latest/tui-code-snippet.js"></script>
    <script src="https://uicdn.toast.com/tui.dom/v3.0.0/tui-dom.js"></script>
    <script src="https://uicdn.toast.com/tui.time-picker/latest/tui-time-picker.min.js"></script>
    <script src="https://uicdn.toast.com/tui.date-picker/latest/tui-date-picker.min.js"></script>
    <script src="https://uicdn.toast.com/tui-calendar/latest/tui-calendar.js"></script>

    <script src=//cdnjs.cloudflare.com/ajax/libs/seedrandom/2.3.10/seedrandom.min.js></script>

    <script>
        let calendar = new tui.Calendar('#calendar', {
            defaultView: 'month',
            // isReadOnly: true,
            month: {
                daynames: [
                    "Sonntag",
                    "Montag",
                    "Dienstag",
                    "Mittwoch",
                    "Donnerstag",
                    "Freitag",
                    "Samstag"
                ],
                startDayOfWeek: 1, // monday
                visibleScheduleCount: 100,
            },
            taskView: true,
            useCreationPopup: false,
            useDetailPopup: true,
            template: {

            }
        });

        calendar.on({
{#            'clickSchedule': function(e) {#}
{#                console.log('clickSchedule', e);#}
{#                /* step1. open custom detail popup */#}
{#                const willModify = confirm(`title: ${e.schedule.title}\nwhen: ${yyyymmdd(new Date(e.schedule.start))} \nWill you update schedule?`);#}
{##}
{#                if (willModify) { // step1-1. open edit popup */#}
{#                    e.schedule.title = prompt('Schedule', e.schedule.title);#}
{#                    calendar.updateSchedule(e.schedule.id, e.schedule.calendarId, e.schedule);#}
{#                }#}
{#            },#}
            'beforeCreateSchedule': function(e) {
                console.log('beforeCreateSchedule', e);
                /* step1. open custom edit popup */
                const title = prompt('Create new task');
                const is_private = $('input[name=calType]:checked').val() === 'private';
                if (title) {
                    let schedule = {
                        id: +new Date(),
                        title: (is_private ? '(P)' : '') + title,
                        isAllDay: true,
                        start: e.start,
                        end: e.end,
                        category: 'time'
                    };
                    166
                    377
                    const obj = {
                        message: title,
                        todo_date: `${e.start.getFullYear()}-${e.start.getMonth()+1}-${e.start.getDate()}`,
                        'private': is_private
                    };
                    if (obj.private) {
                        private_tasks.push(schedule);
                    } else {
                        tasks.push(schedule);
                    }
                    const url = "{% url 'mainapp:create_calendar_task' %}";
                    $.post(url , obj, function( data ) {
                        console.log("created!");
                    });
                    /* step2. save schedule */
                    calendar.createSchedules([schedule]);
                    /* step3. clear guide element */
                    e.guide.clearGuideElement();
                }
            },
{#            'beforeUpdateSchedule': function(e) {#}
{#                console.log('beforeUpdateSchedule', e);#}
{#                e.schedule.start = e.start;#}
{#                e.schedule.end = e.end;#}
{#                calendar.updateSchedule(e.schedule.id, e.schedule.calendarId, e.schedule);#}
{#            },#}
{#            'beforeDeleteSchedule': function(e) {#}
{#                console.log('beforeDeleteSchedule', e);#}
{#                calendar.deleteSchedule(e.schedule.id, e.schedule.calendarId);#}
{#            }#}
        });

        function yyyymmdd(dateIn) {
            var yyyy = dateIn.getFullYear();
            var mm = dateIn.getMonth()+1; // getMonth() is zero-based
            var dd  = dateIn.getDate();
            return String(10000*yyyy + 100*mm + dd); // Leading zeros for mm and dd
        }

        let purchases = JSON.parse('{{ purchases|safe }}').map(function(each) {
            let body;

            if (each.purchase.dc) {
                body = '<p>' +
                    `{% trans "Street" %} - ${each.customer.street}<br>` +
                    `{% trans "Postcode" %} - ${each.customer.postcode}<br>` +
                    `{% trans "Place" %} - ${each.customer.place}<br>` +
                    '</p>-------------' +
                    '<p>' +
                    `{% trans "DC Term" %} - ${each.purchase.dc_term}<br>` +
                    `{% trans "DC Mechanic" %} - ${each.purchase.dc_mechanic}<br>` +
                    '</p>'
            } else {
                body = '<p>' +
                    `{% trans "Street" %} - ${each.customer.street}<br>` +
                    `{% trans "Postcode" %} - ${each.customer.postcode}<br>` +
                    `{% trans "Place" %} - ${each.customer.place}<br>` +
                    '</p>-------------' +
                    '<p>' +
                    `{% trans "AC Term" %} - ${each.purchase.ac_term}<br>` +
                    `{% trans "AC Mechanic" %} - ${each.purchase.ac_mechanic}<br>` +
                    '</p>'
            }

            return {
                id: each.id,
                calendarId: '1',
                title: (each.purchase.dc ? '[DC] ' : '[AC] ') + each.name + '-' + each.customer_id,
                body: body,
                category: 'time',
                dueDateClass: '',
                start: each.dc_term,
                end: each.dc_term,
                isAllDay: true,
                isReadOnly: true,
                color: '#'+(new Math.seedrandom(each.customer_id)()*0xFFFFFF<<0).toString(16),
                bgColor: '#ddd'
            }
        });

        let tasks = JSON.parse('{{ tasks|safe }}').map(function(each) {
            let body = '<p>' +
                `{% trans "Manager" %} - ${each.user}<br>` +
                `{% trans "Time" %} - ${each.time}<br>` +
                `{% trans "Creator" %} - ${each.creator}<br>` +
                '</p>';
            const prefix = each.private ? '(P) ' : '';

            return {
                id: each.id,
                calendarId: '1',
                title: prefix + each.message,
                body: body,
                category: 'time',
                dueDateClass: '',
                start: each.date,
                end: each.date,
                isAllDay: true,
                isReadOnly: true,
                color: '#'+(new Math.seedrandom(each.user)()*0xFF00FF<<0).toString(16),
                bgColor: '#ddd'
            }
        });

        let private_tasks = JSON.parse('{{ private_tasks|safe }}').map(function(each) {
            let body = '<p>' +
                `{% trans "Manager" %} - ${each.user}<br>` +
                `{% trans "Time" %} - ${each.time}<br>` +
                `{% trans "Creator" %} - ${each.creator}<br>` +
                '</p>';

            return {
                id: each.id,
                calendarId: '1',
                title: '(P) ' + each.title,
                body: body,
                category: 'time',
                dueDateClass: '',
                start: each.date,
                end: each.date,
                isAllDay: true,
                isReadOnly: true,
                color: '#'+(new Math.seedrandom(each.user)()*0xFFFFFF<<0).toString(16),
                bgColor: '#ddd'
            }
        });

        calendar.createSchedules(purchases);

        function showPurchase() {
            calendar.clear();
            calendar.createSchedules(purchases, true);
            calendar.render();
        }

        function showTasks() {
            calendar.clear();
            calendar.createSchedules(tasks, true);
            calendar.render();
        }

        function showPrivateTasks() {
            calendar.clear();
            calendar.createSchedules(private_tasks, true);
            calendar.render();
        }

        const monthNames = [
            "Januar", "Februar", "März", "April", "Mai", "Juni",
            "Juli", "August", "September", "Oktober", "November", "Dezember"
        ];

        function moveToNextOrPrevRange(val) {
            if (val === -1) {
                calendar.prev();
            } else if (val === 1) {
                calendar.next();
            }
            let x = calendar.getDate();

            $('#cal-year').text(x.getFullYear());
            $('#cal-month').text(monthNames[x.getMonth()]);
        }

        function onClickTodayBtn() {
            calendar.today();
            let x = calendar.getDate();
            $('#cal-year').text(x.getFullYear());
            $('#cal-month').text(monthNames[x.getMonth()]);

        }

{#        make purchase radio buton selected by default #}
        $(document).ready(function () {
            $('#cal_purchase').attr('checked', true);
        });
    </script>
{% endblock %}