chat/urls.py
# chat/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('unread_rooms/', views.unread_chat_rooms, name='unread_rooms'),
    path('<str:user>/', views.room, name='room'),
    path('', views.index, name='index'),
]

mainapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from mainapp.view import login, home, add_manager, add_customer, \
    add_purchase, call_notes, attachments, task, calendars
from mainapp.view.import_export.export_data import export_xls, import_xls
from mainapp.view.pdfs import offers


app_name = 'mainapp'
urlpatterns = [
    path('', include(('mainapp.urls2', 'mainapp'), namespace='new')),

    path('heartbeat/', login.heartbeat, name='heartbeat'),
    path('', login.LoginView.as_view(), name='login'),
    path('logout', login.logout_view, name='logout'),

    # Home
    path('home/', home.HomeView.as_view(), name='home'),
    path('home/customer/<customer_id>/', home.CustomerHomeView.as_view(), name='customer_home'),

    path('manager/', add_manager.CreateManagerView.as_view(), name='add_manager'),
    path('manager/<int:pk>/', add_manager.UpdateManagerView.as_view(), name='edit_manager'),
    path('delete_manager/<manager_id>', add_manager.delete_manager, name='delete_manager'),

    path('customers/', add_customer.ListCustomerView.as_view(), name='list_customer'),
    path('customer/', add_customer.AddCustomerView.as_view(), name='add_customer'),
    path('customer/<int:pk>/', add_customer.UpdateCustomerView.as_view(), name='edit_customer'),
    path('update_customer/<int:pk>/', add_customer.update_customer, name='patch_customer'),
    path('delete/customer/<int:pk>/', add_customer.DeleteCustomerView.as_view(), name='delete_customer'),

    path('add_purchase/', add_purchase.AddPurchaseView.as_view(), name='add_purchase'),
    path('purchases/', add_purchase.ListPurchaseView.as_view(), name='list_purchase'),
    path('purchases/<int:pk>/', add_purchase.UpdatePurchaseView.as_view(), name='edit_purchase'),
    path('update_purchase/<int:pk>/', add_purchase.update_purchase, name='patch_purchase'),
    path('delete/purchases/<int:pk>/', add_purchase.DeletePurchaseView.as_view(), name='delete_purchase'),

    path('task_list/', task.TasksView.as_view(), name='open_task_list'),
    path('task/<int:pk>/', task.TaskUpdateView.as_view(), name='edit_task'),
    path('delete/task/<int:pk>/', task.DeleteTaskView.as_view(), name='delete_task'),
    path('mark_complete/<int:pk>/', task.mark_completed, name='mark_completed'),
    path('create_calendar_task/', task.create_task, name='create_calendar_task'),

    path('call_notes/<customer_id>/', call_notes.CallNotesCreateView.as_view(), name='add_call_notes'),
    path('call_notes/<customer_id>/<int:pk>/', call_notes.CallNotesUpdateView.as_view(), name='edit_call_notes'),
    path('delete/call_notes/<customer_id>/<int:pk>/', call_notes.CallNotesDeleteView.as_view(), name='delete_call_notes'),

    path('chat/', include(('chat.urls', 'chat'), 'chat')),

    path('<int:customer_id>/attachments/', attachments.AttachmentCreateView.as_view(), name='add_attachments'),
    path('<int:customer_id>/attachments/<int:pk>/', attachments.UpdateAttachmentView.as_view(), name='edit_attachments'),
    path('delete/<int:customer_id>/attachments/<int:pk>/', attachments.DeleteAttachmentView.as_view(), name='delete_attachments'),
    path('email/<int:customer_id>/attachment/<int:pk>/', attachments.email_attachment, name='email_attachment'),

    # attachment type settings
    path('attachment_type/', attachments.UpdateAttachmentTemplateView.as_view(), name='attachment_type'),

    # calendar
    path('calendar/', calendars.calendar, name='calendar'),

    # export and import urls
    path('export_data/', export_xls, name='export_xls'),
    path('import_data/', import_xls, name='import_xls'),

    path('offer/<customer_id>/', offers.download_offer, name='pdf_offer'),
    path('offer_confirm/<customer_id>/', offers.download_offer_confirm, name='pdf_offer_confirm'),
    path('install/<customer_id>/', offers.download_install, name='pdf_install'),
    path('invoice/<customer_id>/', offers.download_invoice, name='pdf_invoice'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

windows_crm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from des import urls as des_urls

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    path('django-des/', include(des_urls)),
    path("tinymce/", include("tinymce.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mainapp/forms/add_customer.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column, HTML

from mainapp.forms.mixins import LabelAdder
from mainapp.models import Customer, GENDER_CHOICES, PURPOSE_CHOICES


class CustomerForm(LabelAdder, forms.ModelForm):
    class Meta:
        model = Customer
        fields = ['purpose', 'gender', 'first_name', 'surname', 'offer_id', 'invoice_id', 'street',
                  'place', 'postcode', 'phone', 'mobile', 'email', 'birthday']
        widgets = {
            'birthday': forms.DateInput(attrs={'type': 'date'})
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # converting to string because form cannot handle date internationalization
        if self.instance and self.instance.id:
            self.initial['birthday'] = str(self.initial['birthday'])


class CustomerAddForm(CustomerForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name in self.fields.keys():
            self.fields[field_name].widget.attrs['class'] = 'form-control'


class CustomerUpdateForm(CustomerForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Column(
                *[Row(field_name, css_class='form-group')
                  for field_name in list(self.fields.keys())[:len(self.fields.keys())//2 + 1]],
                css_class='col-md-6'
            ), Column(
                *[Row(field_name, css_class='form-group')
                  for field_name in list(self.fields.keys())[(len(self.fields.keys()) // 2 + 1):]],
                css_class='col-md-6'
            ),
        )

mainapp/forms/add_manager.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Row, Column

from mainapp.forms.mixins import LabelAdder
from mainapp.models import User


class ManagerForm(LabelAdder, forms.ModelForm):
    class Meta:
        model = User
        fields = ["first_name", "surname", "phone", 'username', 'email', 'password']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.instance and self.instance.id is not None:
            self.fields['email'].widget.attrs['readonly'] = True
            self.initial['password'] = ""
        for field_name in self.fields.keys():
            self.fields[field_name].widget.attrs['class'] = 'form-control'

        self.helper = FormHelper()
        self.helper.layout = Layout(
            Column(
                *[Row(field_name, css_class='form-group')
                  for field_name in list(self.fields.keys())[:len(self.fields.keys()) // 2 + 1]],
                css_class='col-md-6'
            ), Column(
                *[Row(field_name, css_class='form-group')
                  for field_name in list(self.fields.keys())[(len(self.fields.keys()) // 2 + 1):]],
                css_class='col-md-6'
            ),
        )

    def clean_email(self):
        if self.instance and self.instance.id:
            return self.instance.email
        return self.cleaned_data['email']

mainapp/forms/add_purchase_record.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column, HTML

from mainapp.forms.mixins import LabelAdder
from mainapp.models import PurchaseRecord


class PurchaseRecordForm(LabelAdder, forms.ModelForm):
    class Meta:
        model = PurchaseRecord
        exclude = ['created_at', 'is_active']
        widgets = {
            'offer_date': forms.DateInput(attrs={'type': 'date'}),
            'date_sent': forms.DateInput(attrs={'type': 'date'}),
            'dc_term': forms.DateInput(attrs={'type': 'date'}),
            'ac_term': forms.DateInput(attrs={'type': 'date'}),
            'project_planning_created': forms.Select(choices=((True, _('Yes')), (False, _('No')))),
            'date_of_receipt': forms.DateInput(attrs={'type': 'date'})
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, field in self.fields.items():
            self.fields[name].widget.attrs['class'] = 'form-control'
        if self.instance and self.instance.id:
            # customer is not required
            self.fields['customer'].required = False
            self.fields['reseller_name'].required = False
            self.fields['ac_mechanic'].required = False
            self.fields['dc_mechanic'].required = False
            # forms cannot handle i18n date change
            self.initial['offer_date'] = str(self.initial['offer_date'])
            self.initial['date_sent'] = str(self.initial['date_sent'])
            self.initial['dc_term'] = str(self.initial['dc_term'])
            self.initial['ac_term'] = str(self.initial['ac_term'])
        self.helper = FormHelper()
        self.helper.layout = Layout(
            # Row(
            #     Column('customer', css_class='form-group selectpicker col-md-12 mb-0', data_live_search="true"),
            #     css_class='form-row'
            # ),
            HTML('<h3>Module</h3>'),
            Row(
                Column('module_manufacturer', css_class='form-group col-md-12 mb-0'),
                css_class='form-row'
            ),
            Row(
                Column('watt', css_class='form-group col-md-3 mb-0'),
                HTML('<div class="col-md-1 mb-0"></div>'),
                Column('module_count', css_class='form-group col-md-4 mb-0'),
                HTML('<div class="col-md-2 mb-0"></div>'
                     '<p>'
                     'KWP:  <strong><div id="id_kwp"></div></strong>'
                     '</p>'
                     '<br/>'),
                css_class='form-row'
            ),
            HTML('<h3>%s</h3>' % _("Choose if there is battery system or not")),
            'with_battery',
            HTML(f'<h3>{_("With Battery")}</h3>'),
            Row(
                Column('manufacturer', css_class='form-group col-md-6 mb-0'),
                Column('kwh', css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            ),
            HTML('<h3>%s</h3>' % _("WR - Without Battery")),
            Row(
                Column('manufacturer2', css_class='form-group col-md-6 mb-0'),
                Column('kwh2', css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            ),
            HTML('<h3>%s</h3>' % _("Price")),
            'price_without_tax',
            HTML('<p>{}: 19%<br/>'.format(_("Tax"))),
            'offer_by',
            HTML('<h4>%s</h4><br/>' % _("Offer Details")),
            Row(
                Column('offer_date', css_class='form-group col-md-4 mb-0'),
                Column('reseller_name', css_class='form-group col-md-6 mb-0'),
                Column('declined', css_class='form-group col-md-2 mb-0'),
                css_class='form-row'
            ),
            HTML('<h4></h4><br/>' % _("Technical Details")),
            Row(
                Column('date_sent', css_class='form-group col-md-6 mb-0'),
                Column('project_planning_created', css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            ),
            Row(
                Column('dc_term', css_class='form-group col-md-6 mb-0'),
                Column('dc_mechanic', css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            ),
            Row(
                Column('ac_term', css_class='form-group col-md-6 mb-0'),
                Column('ac_mechanic', css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            ),
            Row(
                Column('date_of_receipt', css_class='form-group col-md-6 mb-0')
            ),
            HTML('<h4></h4><br/>' % _("Information of the Roof")),
            'roof_type',
            Row(
                Column('roof_tilt', css_class='form-group col-md-4 mb-0'),
                Column('alignment', css_class='form-group col-md-4 mb-0'),
                Column('module_area', css_class='form-group col-md-4 mb-0'),
                css_class='form-row'
            ),
            Row(
                Column('', css_class='form-group col-md-4 mb-0'),
                Column('', css_class='form-group col-md-4 mb-0'),
                HTML('<p>'
                     '%s: <div id="total_area"></div>' % _("Total Area of all modules") +
                     '</p>'
                     '<br/>'),
                css_class='form-row'
            ),
            'extra_details',
        )

    def clean(self):
        result = super(PurchaseRecordForm, self).clean()
        # if customer is not being updated from the front
        if not result.get('customer') and self.instance and self.instance.id:
            result['customer'] = self.instance.customer
        return result

mainapp/forms/attachments.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Column, Row
from django import forms

from mainapp.models import Attachments, AttachmentTemplate


class AttachmentForm(forms.ModelForm):
    class Meta:
        model = Attachments
        fields = ['file_name', 'upload']

    def __init__(self, *args, **kwargs):
        self.customer_id = kwargs.pop("customer_id", None)
        self.request = kwargs.pop("request", None)
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.customer_id = self.customer_id
        if self.request:
            instance.uploaded_by = self.request.user
        instance.save()


class AttachmentTemplateForm(forms.ModelForm):
    class Meta:
        model = AttachmentTemplate
        fields = ['subject', 'body']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name in self.fields.keys():
            self.fields[field_name].widget.attrs['class'] = 'form-control'

        self.helper = FormHelper()
        self.helper.layout = Layout(
            Column(
                *[Row(field_name, css_class='form-group')
                  for field_name in list(self.fields.keys())],
                css_class='col-md-12'
            )
        )

mainapp/forms/call_notes.py
from django import forms

from mainapp.forms.mixins import LabelAdder
from mainapp.models import CallNotes


class AddCallNotesForm(LabelAdder, forms.ModelForm):
    class Meta:
        model = CallNotes
        fields = ['notes', 'status']

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request", None)
        self.customer_id = kwargs.pop("customer_id", None)
        if not self.request or not self.customer_id:
            raise AttributeError("request missing")
        super().__init__(*args, **kwargs)
        for field_name in self.fields.keys():
            self.fields[field_name].widget.attrs['class'] = 'form-control'

    def save(self, commit=True):
        instance = super(AddCallNotesForm, self).save(commit=False)
        instance.user = self.request.user
        instance.customer_id = self.customer_id
        instance.save()

mainapp/forms/login.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

from mainapp.models import User


class LoginForm(forms.Form):
    username = forms.CharField(label=_('username'),
                               required=True,
                               max_length=255,
                               widget=forms.TextInput(
                                   attrs={
                                       'class': 'form-control',
                                       'placeholder': _('Username')
                                   }
                               ))

    password = forms.CharField(label=_('password'),
                               required=True,
                               max_length=255,
                               widget=forms.PasswordInput(
                                   attrs={
                                       'class': 'form-control',
                                       'placeholder': _('Password')
                                   }
                               ))

    def clean(self):
        username = self.cleaned_data['username']
        if not User.objects.filter(username__iexact=username).exists():
            raise ValidationError(
                "Username/Password does not match"
            )
        user = User.objects.get(username__iexact=username)
        password = self.cleaned_data['password']
        if not user.check_password(raw_password=password):
            raise ValidationError(
                "Username/Password does not match"
            )
        return self.cleaned_data

mainapp/views.py
from django.shortcuts import render

# Create your views here.

mainapp/templates/customer/add_customer.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block content %}

    <div class="dashboard-content-container" data-simplebar>
		<div class="dashboard-content-inner" >
            <h1>{{ operation }} {% if object %}{{ object }}{% endif %}</h1>
            <br/>
            <form id="id_create_customer" method="POST" class="contact100-form validate-form">
                {% csrf_token %}
                {{ form }}
                <br>
                <button type="submit" class="button">{% trans 'Submit' %}</button>
			</form>
        </div>
    </div>

{% endblock %}

mainapp/templates/customer/list_customer.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block content %}

    <div class="dashboard-content-container" data-simplebar>
		<div class="dashboard-content-inner" >
            <div class="row col-md-12">
                <p>
                    <a class="button" href="{% url 'mainapp:add_customer' %}">{% blocktrans %}Add Customer{% endblocktrans %}</a>&nbsp;&nbsp;
                    <a class="button" target="_blank" href="{% url 'mainapp:export_xls' %}">{% blocktrans %}Export{% endblocktrans %}</a>&nbsp;&nbsp;
                </p>
                <form action="{% url 'mainapp:import_xls' %}" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-6">
                            <input type="file" name="xls_file" title="Import" />&nbsp;&nbsp;
                        </div>
                        <div class="col-6">
                            <button class="button" type="submit" >{% blocktrans %}Import{% endblocktrans %}</button>&nbsp;&nbsp;
                        </div>
                    </div>
                </form>
            </div>
            <br>
            <button class="btn btn-outline-secondary" onclick="toggleFilter()">{% trans 'Search' %}</button>
            <div class="filter" id="filter" style="display: none">
                <form method="get">
                    {{ filter_form }}
                    <input type="submit" value={% trans "Submit" %} />
                </form>
            </div>
            <div class="tasks-list-container compact-list margin-top-35">
                {% if not object_list %}
                    <div class="task-listing">{% blocktrans %}No {{ object_type }}(s) Found{% endblocktrans %}</div>
                {% endif %}
                    <div class="task-listing">
                    <!-- Job Listing Details -->
                        <div class="task-listing-details">
                            <!-- Details -->
                            <div class="task-listing-description">
                                <table class="table" style="border-collapse: collapse">
                                    <thead class="thead-dark">
                                        <tr>
                                            <th>{% trans 'ID' %}</th>
                                            <th>{% trans 'Name' %}</th>
                                            <th>{% trans 'offer id'  %}</th>
                                            <th>{% trans 'Invoice ID'  %}</th>
                                            <th>{% trans 'Street' %}</th>
                                            <th>{% trans 'Postcode' %}</th>
                                            <th>{% trans 'Mobile' %}</th>
                                            <th>{% trans 'Email' %}</th>
                                            <th></th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for obj in object_list %}
                                        <tr>
                                            <td>{{ obj.id }}</td>
                                            <td>{{ obj }}</td>
                                            <td>{{ obj.offer_id }}</td>
                                            <td>{{ obj.invoice_id }}</td>
                                            <td>{{ obj.street }}</td>

                                            <td>{{ obj.postcode }}</td>
                                            <td>{{ obj.mobile }}</td>
                                            <td>{{ obj.email }}</td>
                                            <td>
                                                <a href="{% url 'mainapp:edit_customer' pk=obj.id %}" class=""><i class="icon-feather-edit"></i> <span>{% trans 'Edit' %}</span></a>
                                            </td>
                                            <td>
                                                <a href="{% url 'mainapp:delete_customer' pk=obj.id %}" class=""><i class="icon-material-outline-delete"></i> <span>{% trans 'Delete' %}</span></a>
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    <tbody>
                                </table>
                            </div>
                        </div>
                    </div>
            </div>
            <br>
            {# ------------------- PAGINATION ----------------- #}
            {% if page_obj.paginator.num_pages > 1 %}
            <div class="pagination">
                <nav aria-label="Page navigation">
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}"> &laquo; </a></li>
                        {% else %}
                            <li class="page-item" disabled><a class="page-link" aria-disabled="true"> &laquo; </a></li>
                        {% endif %}

                        <li class="page-item"><a class="page-link">{{ page_obj.number }}</a></li>

                        {% if page_obj.has_next %}
                            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}"> &raquo; </a></li>
                        {% else %}
                            <li class="page-item" disabled><a class="page-link" aria-disabled="true"> &raquo; </a></li>
                        {% endif %}
                        <br>
                    </ul>
                    <br>
                </nav>
                <br>
            </div>
            {% endif %}
        </div>
    </div>

{% endblock %}

{% block script %}
    <script>
        function toggleFilter() {
            let x = document.getElementById("filter");
            if (x.style.display === "none") {
                x.style.display = "block";
            } else {
                x.style.display = "none";
            }
        }
    </script>
{% endblock %}